### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space after multiple files parsing.

### ISSUE THREAD

**Issue by wpoosanguansit** [knutwalker/akka-stream-json#2]
I am not really sure if this is related to the parser itself.  I do have the code below now:

```
FileIO.fromFile(filePath.toFile)
        .withAttributes(Attributes.logLevels(onElement = Logging.DebugLevel))
        .via(JsonStreamParser[JsValue])
        .runWith(Sink.foreach(println))
        .fallbackTo(Future { Files.deleteIfExists(filePath) })
```

When I ran this with 16 files of size 9.6 mb dropped at one time into the specified folder.  It ran for while and threw:

Uncaught error from thread [Sys-akka.actor.default-dispatcher-12] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Sys]
[error] java.lang.OutOfMemoryError: Java heap space
[error]         at java.util.Arrays.copyOf(Arrays.java:3332)
[error]         at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
[error]         at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
[error]         at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
[error]         at java.lang.StringBuilder.append(StringBuilder.java:136)
[error]         at spray.json.JsonPrinter$class.printString(JsonPrinter.scala:62)
[error]         at spray.json.CompactPrinter$.printString(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$$anonfun$printObject$2.apply(CompactPrinter.scala:37)
[error]         at spray.json.CompactPrinter$$anonfun$printObject$2.apply(CompactPrinter.scala:36)
[error]         at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:92)
[error]         at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:90)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
[error]         at spray.json.JsonPrinter$class.printSeq(JsonPrinter.scala:90)
[error]         at spray.json.CompactPrinter$.printSeq(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$class.printObject(CompactPrinter.scala:36)
[error]         at spray.json.CompactPrinter$.printObject(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$class.print(CompactPrinter.scala:28)
[error]         at spray.json.CompactPrinter$.print(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$$anonfun$printObject$2.apply(CompactPrinter.scala:39)
[error]         at spray.json.CompactPrinter$$anonfun$printObject$2.apply(CompactPrinter.scala:36)
[error]         at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:92)
[error]         at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:90)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
[error]         at spray.json.JsonPrinter$class.printSeq(JsonPrinter.scala:90)
[error]         at spray.json.CompactPrinter$.printSeq(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$class.printObject(CompactPrinter.scala:36)
[error]         at spray.json.CompactPrinter$.printObject(CompactPrinter.scala:51)
[error]         at spray.json.CompactPrinter$class.print(CompactPrinter.scala:28)
[error]         at spray.json.CompactPrinter$.print(CompactPrinter.scala:51)
java.lang.RuntimeException: Nonzero exit code returned from runner: 255
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) Nonzero exit code returned from runner: 255
[error] Total time: 556 s, completed Jun 11, 2016 10:46

Thanks for any help or suggestion.

**Comment by wpoosanguansit** [comment]
A little more investigation, I was able to run:

```
val fileParser = Source.actorRef[Path](0, OverflowStrategy.dropNew) // use proper settings for your application
      .flatMapConcat(p => FileIO.fromFile(p.toFile))
      .via(JsonStreamParser[JsValue])
      .to(Sink.foreach(println))
      .run()
```

with 200 files dropped into the folder.  So I believe it has more to do with how I use the FileIO directly in this case that caused the jvm to run out of memory.  Thanks.
